### ISSUE TITLE
In the `where` clause of criteria, Using ValueObject of record annotated with `@DataType` will occur `DOMA1007`.

### ISSUE THREAD

**Issue by mazeneko** [domaframework/doma#1216]
**Describe the bug**
In the `where` clause of criteria,
Using ValueObject of record annotated with `@DataType` will occur `DOMA1007`.
Also, when annotated with `@Domain`, it works as expected.

**Expected behavior**
I expect that `DOMA1007` will not occur and will work.

**To Reproduce**
Will reproduce on [Repository by forking getting-started](https://github.com/mazeneko/doma-data-type-issue).
See the commit history for details.

**Screenshots**
```
PS C:\doma-data-type-issue> ./gradlew run

> Task :java-17:run FAILED
Exception in thread "main" org.seasar.doma.internal.jdbc.scalar.ScalarException: [DOMA1007] The wrapper class for the type "boilerplate.java17.entity.Employee$Name" is not found.
        at org.seasar.doma.internal.jdbc.scalar.Scalars.wrap(Scalars.java:73)
        at org.seasar.doma.jdbc.criteria.context.Operand$Param.createInParameter(Operand.java:29)
        at org.seasar.doma.jdbc.criteria.query.BuilderSupport.param(BuilderSupport.java:195)
        at org.seasar.doma.jdbc.criteria.query.BuilderSupport$OperandVisitor.visit(BuilderSupport.java:210)
        at org.seasar.doma.jdbc.criteria.query.BuilderSupport$OperandVisitor.visit(BuilderSupport.java:207)
        at org.seasar.doma.jdbc.criteria.context.Operand$Param.accept(Operand.java:40)
        at org.seasar.doma.jdbc.criteria.query.BuilderSupport$CriterionVisitor.comparison(BuilderSupport.java:371)
        at org.seasar.doma.jdbc.criteria.query.BuilderSupport$CriterionVisitor.visit(BuilderSupport.java:230)
        at org.seasar.doma.jdbc.criteria.context.Criterion$Eq.accept(Criterion.java:24)
        at org.seasar.doma.jdbc.criteria.query.BuilderSupport.visitCriterion(BuilderSupport.java:204)
        at org.seasar.doma.jdbc.criteria.query.SelectBuilder.visitCriterion(SelectBuilder.java:242)
        at org.seasar.doma.jdbc.criteria.query.SelectBuilder.where(SelectBuilder.java:143)
        at org.seasar.doma.jdbc.criteria.query.SelectBuilder.interpret(SelectBuilder.java:72)
        at org.seasar.doma.jdbc.criteria.query.SelectBuilder.build(SelectBuilder.java:64)
        at org.seasar.doma.jdbc.criteria.statement.EntityqlSelectTerminal.createCommand(EntityqlSelectTerminal.java:50)
        at org.seasar.doma.jdbc.criteria.statement.EntityqlSelectStarting.createCommand(EntityqlSelectStarting.java:161)
        at org.seasar.doma.jdbc.criteria.statement.AbstractStatement.execute(AbstractStatement.java:36)
        at org.seasar.doma.jdbc.criteria.statement.Listable.fetch(Listable.java:23)
        at boilerplate.java17.repository.EmployeeRepository.selectByName(EmployeeRepository.java:31)
        at boilerplate.java17.Main.lambda$main$0(Main.java:26)
        at org.seasar.doma.jdbc.tx.LocalTransactionManager.lambda$toSupplier$0(LocalTransactionManager.java:242)
        at org.seasar.doma.jdbc.tx.LocalTransactionManager.executeInTransaction(LocalTransactionManager.java:262)
        at org.seasar.doma.jdbc.tx.LocalTransactionManager.requiredInternal(LocalTransactionManager.java:128)
        at org.seasar.doma.jdbc.tx.LocalTransactionManager.required(LocalTransactionManager.java:88)
        at boilerplate.java17.Main.main(Main.java:23)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':java-17:run'.
> Process 'command 'C:\Program Files\Eclipse Adoptium\jdk-17.0.9.9-hotspot\bin\java.exe'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 3s
3 actionable tasks: 2 executed, 1 up-to-date
```

**Environment (please complete the following information):**
- Doma version or git rev: 3.0.1
- Build tool (ie. output of `mvnw --version` or `gradlew --version`): Gradle 8.10.2
- Database version: H2 2.3.232

**Comment by nakamura-to** [comment]
Thank you for your feedback. 
We’ve identified the cause and will fix it in the next version.

（もし可能であれば日本語部分を英語に翻訳してもらってもいいでしょうか？より多くの方に利用いただきたいので英語でやりとりできればと思います。私の方で修正しても構いません。）

**Comment by mazeneko** [comment]
Thanks for the quick reaction!
okay, I will translate! XD
