### ISSUE TITLE
PostgreSQLで、@BatchInsert時にGenerationType.IDENTITYによるID自動生成がされない

### ISSUE THREAD

**Issue by MasatoshiTada** [domaframework/doma#169]
# 概要

@BatchInsert実行時に発行されるINSERT文に、主キーが含まれてしまいます。主キーには0が代入されています。
@Insertでは、発行されるINSERT文に主キーが含まれておらず、自動採番がされています。

下記のコードは、GitHubにアップしてあります。
https://github.com/MasatoshiTada/doma-maven
# 環境
- Doma 2.12.1
- PostgreSQL 9.4.2
- org.postgresql:postgresql:9.4.1211
- macOS Sierra
- Eclipse JEE 4.6.1
- JDK 8u102
# テーブル定義

``` sql
create table employee (
    id serial primary key, -- serial型かつデフォルト値なし
    name varchar(100),
    joined_date date
);
```
# エンティティクラス

``` java
@Entity
public class Employee {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public int id;

    public String name;

    public LocalDate joinedDate;
}
```
# Daoクラス

``` java
@Dao(config = PostgresConfig.class)
public interface PostgresEmployeeDao {
    @Insert
    int insert(Employee employee);

    @BatchInsert(batchSize = 10, exclude = {"id"})
    int[] batchInsert(List<Employee> employeeList);
}
```
# テストコード

``` java
public class PostgresEmployeeDaoTest {
    /**
     * このテストは成功する
     */
    @Test
    public void 社員を1件追加できる() {
        Employee employee = new Employee("太郎", LocalDate.of(2016, 10, 10));
        int rows = txManager.required(() -> {
            return employeeDao.insert(employee);
        });
        assertThat(rows, is(1));
    }

    /**
     * このテストが失敗する
     */
    @Test
    public void 社員を3件一括追加できる() {
        List<Employee> employeeList = Arrays.asList(
                new Employee("太郎", LocalDate.of(2016, 10, 10)),
                new Employee("次郎", LocalDate.of(2016, 10, 11)),
                new Employee("三郎", LocalDate.of(2016, 10, 12)));
        int[] rowsList = txManager.required(() -> {
            return employeeDao.batchInsert(employeeList);
        });
        boolean allOne = Arrays.stream(rowsList).allMatch(rows -> rows == 1);
        assertThat(allOne, is(true));
        assertThat(rowsList.length, is(3));
    }

}
```
# 実行ログ

``` log
org.seasar.doma.jdbc.BatchUniqueConstraintException: [DOMA2029] 一意制約違反によりバッチ更新処理が失敗しました。
SQLファイルパス=[null]。
実際のSQL=[insert into employee (id, name, joined_date) values (?, ?, ?)]。
詳しい原因は次のものです。java.sql.BatchUpdateException: Batch entry 1 insert into employee (id, name, joined_date) values (0, '次郎', '2016-10-11 +09'::date) was aborted: ERROR: duplicate key value violates unique constraint "employee_pkey"
  詳細: Key (id)=(0) already exists.  Call getNextException to see other errors in the batch.
    at org.seasar.doma.jdbc.command.BatchModifyCommand.executeBatch(BatchModifyCommand.java:132)
    at org.seasar.doma.jdbc.command.BatchModifyCommand.executeBatch(BatchModifyCommand.java:114)
    at org.seasar.doma.jdbc.command.BatchInsertCommand.executeInternal(BatchInsertCommand.java:41)
    at org.seasar.doma.jdbc.command.BatchModifyCommand.execute(BatchModifyCommand.java:67)
    at com.example.dao.PostgresEmployeeDaoImpl.batchInsert(PostgresEmployeeDaoImpl.java:165)
    at com.example.dao.PostgresEmployeeDaoTest.lambda$2(PostgresEmployeeDaoTest.java:57)
    at org.seasar.doma.jdbc.tx.LocalTransactionManager.executeInTransaction(LocalTransactionManager.java:245)
    at org.seasar.doma.jdbc.tx.LocalTransactionManager.requiredInternal(LocalTransactionManager.java:96)
    at org.seasar.doma.jdbc.tx.LocalTransactionManager.required(LocalTransactionManager.java:75)
    at com.example.dao.PostgresEmployeeDaoTest.社員を3件一括追加できる(PostgresEmployeeDaoTest.java:56)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.sql.BatchUpdateException: Batch entry 1 insert into employee (id, name, joined_date) values (0, '次郎', '2016-10-11 +09'::date) was aborted: ERROR: duplicate key value violates unique constraint "employee_pkey"
  詳細: Key (id)=(0) already exists.  Call getNextException to see other errors in the batch.
    at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:151)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2159)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:463)
    at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:794)
    at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1662)
    at org.seasar.doma.jdbc.command.BatchModifyCommand.executeBatch(BatchModifyCommand.java:127)
    ... 33 more
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "employee_pkey"
  詳細: Key (id)=(0) already exists.
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2458)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2158)
    ... 37 more
```

**Comment by nakamura-to** [comment]
エンティティクラスで`id`の型を`int`にしているので`int`の初期値である`0`がINSERT文に反映されてしまっていますね。`int`の代わりに`Integer`を使うか、`id`の初期値に`-1`など`0`より小さい値を設定してみてください。
この辺りハマりポイントかもしれませんね。ドキュメントの書き方を工夫できるかもしれません。

**Comment by MasatoshiTada** [comment]
いただいたアドバイスの通り、idを-1またはIntegerに変更したら、上記のテストがGreenになりました。
https://github.com/MasatoshiTada/doma-maven/commit/18bb9490ae599820100ae2e757296e09464f9bee
ありがとうございました！

**Comment by nakamura-to** [comment]
ドキュメントに記載しておきました。 #170
