### ISSUE TITLE
カラム数が多いテーブルを使用した際に「Method code too large!」エラーが発生する

### ISSUE THREAD

**Issue by ushibutatory** [domaframework/doma#172]
300カラムを超えるテーブルに対してEntityクラスを定義した場合、アプリケーション実行時に、生成されるコンストラクタでエラーが発生します。

<pre>
Caused by: java.lang.RuntimeException: Method code too large!
	at sl.org.objectweb.asm.MethodWriter.a(Unknown Source)
	at sl.org.objectweb.asm.ClassWriter.toByteArray(Unknown Source)
	at org.springsource.loaded.ReloadableType$MergedRewrite$ChainedAdapters.getBytes(ReloadableType.java:984)
	at org.springsource.loaded.ReloadableType$MergedRewrite.rewrite(ReloadableType.java:962)
	at org.springsource.loaded.ReloadableType.rewriteCallSitesAndDefine(ReloadableType.java:934)
	at org.springsource.loaded.ReloadableType.<init>(ReloadableType.java:173)
	at org.springsource.loaded.TypeRegistry.addType(TypeRegistry.java:1103)
	at org.springsource.loaded.agent.SpringLoadedPreProcessor.preProcess(SpringLoadedPreProcessor.java:335)
	at org.springsource.loaded.agent.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:107)
	... 119 more
</pre>

生成されたコンストラクタ
<pre>
    private _Entity() {
        ...
        __list.add($column1);
        __map.put("column1", $column1);
        __list.add($column2);
        __map.put("column2", $column2);
        ...（カラム数が多すぎてエラーになっている模様）
</pre>

カラム数を減らす（テーブル定義の変更をする）ことなく回避する方法はありますでしょうか？

* Java 1.8
* Doma 2.6.0
* Spring Boot 1.3.6.RELEASE
* MySQL 5.6

不足情報などあればご指摘ください。
恐れ入りますが何卒よろしくお願いいたします。

**Comment by nakamura-to** [comment]
どれくらいのカラム数であればエラーは発生せずに済みますか？だいたいの閾値を知りたいです。

spring-loadedを利用しない場合は300カラムを超えるテーブルであってもエラーは起きないと考えてよいですか？

**Comment by ushibutatory** [comment]
JVMが1メソッドの長さを64Kと定めているようでした。
http://stackoverflow.com/questions/6570343/maximum-size-of-a-method-in-java
http://stackoverflow.com/questions/17422480/maximum-size-of-a-method-in-java-7-and-8

実際にカラム数を変更しての検証はできていませんが、カラム数だけでなくカラム名の長さにも依存しそうです。

**Comment by nakamura-to** [comment]
もしspring-loaderを使わない場合にこの現象が発生しなければ、spring-loaderを使わないことが回避方法の一つになると思います。

それ以外の方法としては、カラム数が多いテーブルに対してはDomaを使わないという案も考えられます。つまり、エンティティクラスに `@Entity` を注釈するのをやめて、DaoのデフォルトメソッドでDoma提供のクエリビルダや他のDBアクセスライブラリを使う方法です。

デフォルトメソッドを使う例はこちらを参照ください。
http://doma.readthedocs.io/ja/stable/dao/#dao-default-method

上記リンク先の例ではクエリビルダを使っていますが、`config.getDataSource()`とすることで`DataSource`を取得可能ですのでSpringJDBCなど他のDBアクセスライブラリと連携できます。

Domaの近い将来のバージョンではエンティティクラスのメタクラスのコンストラクタの一部を別メソッドに切り出すなどしてエラーが発生しにくくなるような緩和策を導入しようと思います。

**Comment by ushibutatory** [comment]
> もしspring-loaderを使わない場合にこの現象が発生しなければ、spring-loaderを使わないことが回避方法の一つになると思います。

確認が遅くなってすみません。spring-loaderを使わない場合はエラーは発生しませんでした。
使わない方向で回避できるので、このissueはクローズしていただければと思います。
