### ISSUE TITLE
トランザクションロールバック時にランタイム例外が発生することでローカルトランザクションの状態が壊れる

### ISSUE THREAD

**Issue by scnmztn** [domaframework/doma#219]
LocalTransaction#rollbackInternal 内、 try - finally ブロック外での LocalTransactionContext#getConnection がランタイム例外をスローするとスレッドローカルに LocalTransactionContext インスタンスへの参照が残った状態になり、以降同一スレッドにおけるトランザクションが開始できなくなります。

トランザクションが開始された状態で JDBC 接続がサーバーから切断された場合等にこの事象が起きます。このときローカルトランザクションはロールバックしようとしますが、前述の通りロールバック処理自体が失敗し、 LocalTransaction オブジェクトのスレッドローカルに切断されたコネクションを参照した LocalTransactionContext が残ります。

```
org.seasar.doma.jdbc.JdbcException: [DOMA2056] トランザクション分離レベルの取得に失敗しました。原因は次のものです。java.sql.SQLException: Connection is closed
	at org.seasar.doma.jdbc.tx.LocalTransaction.lambda$beginInternal$0(LocalTransaction.java:212)
	at org.seasar.doma.jdbc.tx.LocalTransactionContext.getConnection(LocalTransactionContext.java:78)
	at org.seasar.doma.jdbc.tx.LocalTransaction.rollbackInternal(LocalTransaction.java:346)
	at org.seasar.doma.jdbc.tx.LocalTransaction.rollback(LocalTransaction.java:328)
	at org.seasar.doma.jdbc.tx.LocalTransactionManager.executeInTransaction(LocalTransactionManager.java:251)
	at org.seasar.doma.jdbc.tx.LocalTransactionManager.requiredInternal(LocalTransactionManager.java:96)
	at org.seasar.doma.jdbc.tx.LocalTransactionManager.required(LocalTransactionManager.java:75)
	...
Caused by: java.sql.SQLException: Connection is closed
	at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:475)
	at com.sun.proxy.$Proxy96.getTransactionIsolation(Unknown Source)
	at com.zaxxer.hikari.pool.HikariProxyConnection.getTransactionIsolation(HikariProxyConnection.java)
	at org.seasar.doma.jdbc.tx.LocalTransaction.lambda$beginInternal$0(LocalTransaction.java:209)
	... 21 common frames omitted
```

**Comment by nakamura-to** [comment]
ありがとうございます！
確かに指摘いただいた通りのコードになっていますね。
近日中に修正して新しいバージョンをリリースしようと思います。
