### ISSUE TITLE
Webサーバ固有の特殊なスレッドからDomaを利用すると、ScalarExceptionが発生

### ISSUE THREAD

**Issue by MakotoKinoshita** [domaframework/doma#246]
Webサーバ固有の特殊なスレッドからdoma-2.19.2を利用すると、ScalarExceptionが発生します。

## 再現環境
* Websphere Application Server traditional v9.0 Netowork Deployment (※以降WASと略)

## 事象
WASのDistributedObjectCacheという動的キャッシュ機能を利用し、かつ、オブジェクトの変更を`ChangeListener`というリスナーが呼び出される特殊な実装があります。

上記のリスナーは、WASから呼び出されるのですが、よくあるWebコンテナやEJBコンテナのスレッドではなく、DRSThreadPoolという特殊なスレッドから呼び出されます。

上記の特殊なスレッドからdomaのSelectが実行された場合に、後述のスタックトレースと例外が出力されます。

少なくとも、doma-1.26.0の実装では例外が発生していなかったので、実装が変わったことによる影響かと思います。

## 原因の推測
1.26.0と現在の実装を確認したところ、`DomainTypeFactory#getExternalDomainType`でドメインクラスの取得方法が変わっています。

### 現在の実装:DomainTypeFactory
https://github.com/domaframework/doma/blob/dc854efb3c5967e6ce6cb557d91d9466efa88572/src/main/java/org/seasar/doma/jdbc/domain/DomainTypeFactory.java#L146-L176

### 1.26.0の実装:DomainTypeFactory
https://github.com/domaframework/doma/blob/6a54a20bcbd2b2140331c36df270265ce1a63075/doma/src/main/java/org/seasar/doma/jdbc/domain/DomainTypeFactory.java#L92-L106

さらに追っていくと、`Class.forName`で取得するのか、現在のスレッドのContextClassLoaderの`loadClass`で取得するように実装が変わったようです。
おそらく、この実装変更が影響した可能性が高いと思っています。

https://github.com/domaframework/doma/blob/bbf193b23437493f0b814a314cc2e7118dc817f8/src/main/java/org/seasar/doma/jdbc/ClassHelper.java#L43-L54

## スタックトレース
```
[18/11/07 9:59:40:420 JST]     FFDC Exception:org.seasar.doma.jdbc.JdbcException SourceId:com.ibm.ws.cache.DCEventSource.cacheEntryChanged ProbeId:169 Reporter:com.ibm.ws.cache.DCEventSource@3ac8df4c
org.seasar.doma.jdbc.JdbcException: [DOMA2118] SQLの組み立てに失敗しました。（[10]行目[47]番目の文字付近）。バインド変数コメント[/* appstatusKey.sysId */]を正しく扱えませんでした。原因は次のものです。org.seasar.doma.internal.jdbc.scalar.ScalarException: [DOMA1007] 型[XXXXXXXXXXXXXX.domain.app.value.SysId]の値[00]に対応するラッパークラスが見つかりません。。SQL[SELECT
     XXXXXXXXXXX
FROM
     XXXXXXXXXXX
WHERE
    XXXXXXXXXXX = /* appstatusKey.sysId */'0001'
]
	at org.seasar.doma.internal.jdbc.sql.NodePreparedSqlBuilder.wrap(NodePreparedSqlBuilder.java:721)
	at org.seasar.doma.internal.jdbc.sql.NodePreparedSqlBuilder.handleSingleValueNode(NodePreparedSqlBuilder.java:308)
	at org.seasar.doma.internal.jdbc.sql.NodePreparedSqlBuilder.visitValueNode(NodePreparedSqlBuilder.java:239)
	at org.seasar.doma.internal.jdbc.sql.NodePreparedSqlBuilder.visitBindVariableNode(NodePreparedSqlBuilder.java:208)
	at org.seasar.doma.internal.jdbc.sql.NodePreparedSqlBuilder.visitBindVariableNode(NodePreparedSqlBuilder.java:95)
	at org.seasar.doma.internal.jdbc.sql.node.BindVariableNode.accept(BindVariableNode.java:33)
	at org.seasar.doma.internal.jdbc.sql.NodePreparedSqlBuilder.handleConditionalClauseNode(NodePreparedSqlBuilder.java:563)
	at org.seasar.doma.internal.jdbc.sql.NodePreparedSqlBuilder.visitWhereClauseNode(NodePreparedSqlBuilder.java:510)
	at org.seasar.doma.internal.jdbc.sql.NodePreparedSqlBuilder.visitWhereClauseNode(NodePreparedSqlBuilder.java:95)
	at org.seasar.doma.internal.jdbc.sql.node.WhereClauseNode.accept(WhereClauseNode.java:40)
	at org.seasar.doma.internal.jdbc.sql.NodePreparedSqlBuilder.visitSelectStatementNode(NodePreparedSqlBuilder.java:483)
	at org.seasar.doma.internal.jdbc.sql.NodePreparedSqlBuilder.visitSelectStatementNode(NodePreparedSqlBuilder.java:95)
	at org.seasar.doma.internal.jdbc.sql.node.SelectStatementNode.accept(SelectStatementNode.java:138)
	at org.seasar.doma.internal.jdbc.sql.NodePreparedSqlBuilder.visitAnonymousNode(NodePreparedSqlBuilder.java:176)
	at org.seasar.doma.internal.jdbc.sql.NodePreparedSqlBuilder.visitAnonymousNode(NodePreparedSqlBuilder.java:95)
	at org.seasar.doma.internal.jdbc.sql.node.AnonymousNode.accept(AnonymousNode.java:35)
	at org.seasar.doma.internal.jdbc.sql.NodePreparedSqlBuilder.build(NodePreparedSqlBuilder.java:167)
	at org.seasar.doma.jdbc.query.SqlFileSelectQuery.lambda$prepareSql$0(SqlFileSelectQuery.java:51)
	at org.seasar.doma.jdbc.query.SqlFileSelectQuery$$Lambda$48.00000000A6B16AA0.apply(Unknown Source)
	at org.seasar.doma.jdbc.query.AbstractSelectQuery.buildSql(AbstractSelectQuery.java:105)
	at org.seasar.doma.jdbc.query.SqlFileSelectQuery.prepareSql(SqlFileSelectQuery.java:47)
	at org.seasar.doma.jdbc.query.AbstractSelectQuery.prepare(AbstractSelectQuery.java:82)
	at org.seasar.doma.jdbc.query.SqlFileSelectQuery.prepare(SqlFileSelectQuery.java:38)
	at XXXXXXXXXXXXXX.AppstatusDaoImpl.get(XXXXXXXXXXX)
	・・・
	at XXXXXXXXXXXXXX.objcache.listener.ObjectCacheChangeListener.cacheEntryChanged(XXXXXXXXXXX)
	at com.ibm.ws.cache.DCEventSource.cacheEntryChanged(DCEventSource.java:192)
	at com.ibm.ws.cache.Cache._syncSetEntry(Cache.java:861)
	at com.ibm.ws.cache.Cache.setEntry(Cache.java:512)
	at com.ibm.ws.cache.DCacheBase.setEntry(DCacheBase.java:502)
	at com.ibm.ws.cache.Cache.batchUpdate(Cache.java:1535)
	at com.ibm.ws.cache.CacheUnitImpl.batchUpdate(CacheUnitImpl.java:128)
	at com.ibm.ws.cache.drs.DRSMessageListener.updateEntryProp(DRSMessageListener.java:364)
	at com.ibm.ws.drs.stack.DRSClientCallback.processRcvMessage(DRSClientCallback.java:254)
	at com.ibm.ws.drs.stack.DRSStack.processRcvMessage(DRSStack.java:295)
	at com.ibm.ws.drs.DRSDomain.messageReceived(DRSDomain.java:627)
	at com.ibm.ws.drs.ha.DRSAgentClassEvents$1.run(DRSAgentClassEvents.java:292)
	at java.lang.Thread.run(Thread.java:811)
Caused by: org.seasar.doma.internal.jdbc.scalar.ScalarException: [DOMA1007] 型[XXXXXXXXXXXXXX.domain.app.value.SysId]の値[00]に対応するラッパークラスが見つかりません。
	at org.seasar.doma.internal.jdbc.scalar.Scalars.wrap(Scalars.java:95)
	at org.seasar.doma.internal.jdbc.sql.NodePreparedSqlBuilder.wrap(NodePreparedSqlBuilder.java:717)
	... 39 more

```

## 参考
https://www.ibm.com/support/knowledgecenter/en/SSAW57_9.0.0/com.ibm.websphere.nd.multiplatform.doc/ae/tdyn_distmap.html

**Comment by nakamura-to** [comment]
報告とプルリクエストありがとうございます。

> さらに追っていくと、Class.forNameで取得するのか、現在のスレッドのContextClassLoaderのloadClassで取得するように実装が変わったようです。

原因はご指摘の通りで間違いなさそうです。いただいた修正は取り込む方向で検討しますが、Domaのコードを修正せずに対応する方法もありますので、共有させてください。

次のようにします。

1. プルリクエストいただいような実装を持つ `org.seasar.doma.jdbc.ClassHelper` の実装クラスを作成する
2.  `org.seasar.doma.jdbc.Config` の実装クラスの `getClassHelper` で上記の `ClassHelper` 実装クラスのインスタンスを返す

もしよければお試しください。

**Comment by makotok** [comment]
回答ありがとうございます😊
一旦は自前でClassHelperを用意してみます。

ClassLoaderは奥が深すぎて何が適切なのか難しいところですね。
Webサーバ上だとコンテキスト毎にClassLoaderが違ったりする上に、今回のようなパターンもあるので、必ずしても現在のスレッドのContextClassLoaderからクラスをロードすれば良いのかよく分かっていないです。

**Comment by nakamura-to** [comment]
絶対の正解はないのかもしれないですね。

ClassHelperを導入してロード方法をカスタマイズできるようにしたのは、PlyaframeworkだとClass.forNameは使えないという報告があったからで、ContextClassLoaderから読み込むようにしたのはSpring Dev Toolsに対応するためでした。
