### ISSUE TITLE
Domainクラスへの変換に失敗する

### ISSUE THREAD

**Issue by hogewest** [domaframework/doma#421]
## 概要
Entityに列挙型のDomainをメンバ変数として定義し、かつアノテーションを定義した状態でコンパイルし検索を実行すると、カラム値からDomainクラスへの変換に失敗しました。

Eclipse からコンパイルした場合のみ発生し、Gradle からコンパイルした場合は問題が発生しませんでした。

## 環境
* Java Version: 11.0.7
* Eclipse Version: 2018-12 (4.10.0)
* Doma Version: 2.34.0

## 再現したソース
https://github.com/hogewest/simple-examples/commit/0ebfb3ba5dfe352def03fb34866682fecd86a1cf

[@HogeAnnotation](https://github.com/hogewest/simple-examples/commit/0ebfb3ba5dfe352def03fb34866682fecd86a1cf#diff-27dae1df0b57dc01e2c2c86b8dc9fa19R57) を外すとエラーは発生しなくなります。

### StackTrace
再現したソースの状態で `examples.SelectTest#testSimpleSelect` のテストを実行
```
org.seasar.doma.jdbc.JdbcException: [DOMA2040] The constant "1" is not found in the Enum type "examples.entity.Employee$HogeType".
	at org.seasar.doma.jdbc.type.EnumType.doGetValue(EnumType.java:40)
	at org.seasar.doma.jdbc.type.EnumType.doGetValue(EnumType.java:13)
	at org.seasar.doma.jdbc.type.AbstractJdbcType.getValue(AbstractJdbcType.java:38)
	at org.seasar.doma.jdbc.criteria.command.EntityPoolProvider$JdbcTypeProxy.getValue(EntityPoolProvider.java:126)
	at org.seasar.doma.internal.jdbc.command.JdbcValueGetter.apply(JdbcValueGetter.java:33)
	at org.seasar.doma.jdbc.criteria.command.EntityPoolProvider$JdbcValueGetterProxy.apply(EntityPoolProvider.java:108)
	at org.seasar.doma.jdbc.dialect.StandardDialect$StandardJdbcMappingVisitor.visitEnumWrapper(StandardDialect.java:535)
	at org.seasar.doma.jdbc.dialect.StandardDialect$StandardJdbcMappingVisitor.visitEnumWrapper(StandardDialect.java:397)
	at org.seasar.doma.wrapper.EnumWrapper.accept(EnumWrapper.java:42)
	at org.seasar.doma.jdbc.criteria.command.EntityPoolProvider.fetch(EntityPoolProvider.java:80)
	at org.seasar.doma.jdbc.criteria.command.EntityPoolProvider.get(EntityPoolProvider.java:51)
	at org.seasar.doma.jdbc.criteria.command.EntityPoolProvider.get(EntityPoolProvider.java:29)
	at org.seasar.doma.internal.jdbc.command.ResultSetIterator.next(ResultSetIterator.java:53)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at org.seasar.doma.internal.util.IteratorUtil.toList(IteratorUtil.java:11)
	at org.seasar.doma.internal.util.IteratorUtil.copy(IteratorUtil.java:16)
	at org.seasar.doma.internal.jdbc.command.AbstractIterationHandler.handle(AbstractIterationHandler.java:37)
	at org.seasar.doma.jdbc.command.SelectCommand.handleResultSet(SelectCommand.java:100)
	at org.seasar.doma.jdbc.command.SelectCommand.executeQuery(SelectCommand.java:92)
	at org.seasar.doma.jdbc.command.SelectCommand.execute(SelectCommand.java:52)
	at org.seasar.doma.jdbc.criteria.command.AssociateCommand.execute(AssociateCommand.java:35)
	at org.seasar.doma.jdbc.criteria.command.AssociateCommand.execute(AssociateCommand.java:19)
	at org.seasar.doma.jdbc.criteria.statement.AbstractStatement.execute(AbstractStatement.java:37)
	at org.seasar.doma.jdbc.criteria.statement.Listable.stream(Listable.java:16)
	at org.seasar.doma.jdbc.criteria.statement.Listable.fetchOptional(Listable.java:20)
	at examples.dao.EmployeeDao.selectById(EmployeeDao.java:37)
	at examples.dao.EmployeeDaoImpl.selectById(EmployeeDaoImpl.java:26)
	at examples.SelectTest.lambda$0(SelectTest.java:37)
	at org.seasar.doma.jdbc.tx.LocalTransactionManager.lambda$toSupplier$0(LocalTransactionManager.java:179)
	at org.seasar.doma.jdbc.tx.LocalTransactionManager.executeInTransaction(LocalTransactionManager.java:199)
	at org.seasar.doma.jdbc.tx.LocalTransactionManager.requiredInternal(LocalTransactionManager.java:65)
	at org.seasar.doma.jdbc.tx.LocalTransactionManager.required(LocalTransactionManager.java:25)
	at examples.SelectTest.testSimpleSelect(SelectTest.java:35)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:212)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:208)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
```

## その他調査事項
doma-processor で生成されたソースが Eclispe からコンパイルした場合と Gradle からコンパイルした場合で異なる結果になっていた。

### Eclipse からコンパイルした場合
`.apt_generated\examples\entity\_Employee.java`
```java
    /** the hogeType */
    public final org.seasar.doma.jdbc.entity.DefaultPropertyType<examples.entity.Employee, examples.entity.Employee.HogeType, examples.entity.Employee.HogeType> $hogeType = new org.seasar.doma.jdbc.entity.DefaultPropertyType<>(examples.entity.Employee.class, () -> new org.seasar.doma.internal.jdbc.scalar.BasicScalar<>(() -> new org.seasar.doma.wrapper.EnumWrapper<examples.entity.Employee.HogeType>(examples.entity.Employee.HogeType.class)), "hogeType", "HOGE_TYPE", __namingType, true, true, false);
```

### Gradle からコンパイルした場合
`build\generated\sources\annotationProcessor\java\main\examples\entity\_Employee.java`
```java
    /** the hogeType */
    public final org.seasar.doma.jdbc.entity.DefaultPropertyType<examples.entity.Employee, java.lang.Integer, examples.entity.Employee.HogeType> $hogeType = new org.seasar.doma.jdbc.entity.DefaultPropertyType<>(examples.entity.Employee.class, examples.entity._Employee__HogeType.getSingletonInternal()::createScalar, "hogeType", "HOGE_TYPE", __namingType, true, true, false);
```

**Comment by hogewest** [comment]
理由が分かりませんが、[ここ](https://github.com/domaframework/doma/blob/master/doma-processor/src/main/java/org/seasar/doma/internal/apt/cttype/CtTypes.java#L230) での `getAnnotation` の返り値が Eclipse でコンパイルした場合のみ null が返ってくるのが問題のようです。

**Comment by nakamura-to** [comment]
報告ありがとうございます。`ElementType.TYPE_USE`に関するEclipseの不具合だと思われますが、回避策を入れておきました。

**Comment by hogewest** [comment]
対応ありがとうございました:-)
