### ISSUE TITLE
PostgresDialect で @Table(quote=true), GenerationType.IDENTITY のEntityでID生成エラーが発生する

### ISSUE THREAD

**Issue by drumsco** [domaframework/doma#73]
# 内容

PostgreSQL を操作するために、 Entity に ``@Table(quote = true)`` を指定していて、 ``@Id @GeneratedValue(strategy = GenerationType.IDENTITY) Long id;`` なプロパティを定義している場合に、IDプロパティの生成に失敗する。

```java
@Entity(listener = TableNameListener.class, naming = NamingType.SNAKE_LOWER_CASE)
@Table(name = "table_name", quote = true)
public class TableName {

    /** ID */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    Long id;
```

PostgreSQL で 自動採番を定義する際に ``SERIAL`` 型を指定している。この場合、 "table_name_column_seq" というシーケンスが生成されます。

``@Table(quote=true)`` が指定されていると、 ``PostgresDialect#getIdentitySelectSql(String, String)`` の ``qualifiedTableName`` へクオートされたテーブル名 ( ``"table_name"`` ) が渡されるようです。 

PostgreSQL で予約後になっているキーワード ( "user" や "password" , "group" など ) をテーブル名やカラム名に利用する場合、または大文字小文字を考慮した実装だと思います。

[Returning rows in PostgreSQL with a table called "user" - Database Administrators Stack Exchange](http://dba.stackexchange.com/questions/75551/returning-rows-in-postgresql-with-a-table-called-user)

しかし、 ``getIdentitySelectSql`` 内部では、シーケンスから採番するために以下のSQLを生成します。

```sql
select currval('table_name_column_seq');
```

この処理でテーブル名がダブルクオートで囲われる場合を考慮できていないようです。その結果

```sql
select currval('"table_name"_column_seq');
```

のようなSQLが生成されていました。

# 環境

- java version "1.8.0_31"
- org.seasar.doma:doma:2.2.0
- org.postgresql:postgresql:9.3-1103-jdbc41
- PostgreSQL 9.3

# エラーログ

```log
org.seasar.doma.jdbc.JdbcException: [DOMA2018] エンティティ[User]のIDプロパティの生成に失敗しました。原因は次のものです。org.postgresql.util.PSQLException: ERROR: 名前構文が無効です
  ポジション: 16
	at org.seasar.doma.jdbc.id.AbstractIdGenerator.getGeneratedValue(AbstractIdGenerator.java:61)
	at org.seasar.doma.jdbc.id.BuiltinIdentityIdGenerator.getGeneratedValue(BuiltinIdentityIdGenerator.java:101)
	at org.seasar.doma.jdbc.id.BuiltinIdentityIdGenerator.generatePostInsert(BuiltinIdentityIdGenerator.java:62)
	at org.seasar.doma.jdbc.entity.GeneratedIdPropertyType.lambda$postInsert$9(GeneratedIdPropertyType.java:203)
	at org.seasar.doma.jdbc.entity.GeneratedIdPropertyType$$Lambda$65/921500150.get(Unknown Source)
	at org.seasar.doma.jdbc.entity.GeneratedIdPropertyType$ValueSetter.visitNumberWrapper(GeneratedIdPropertyType.java:233)
	at org.seasar.doma.jdbc.entity.GeneratedIdPropertyType$ValueSetter.visitNumberWrapper(GeneratedIdPropertyType.java:223)
	at org.seasar.doma.wrapper.NumberWrapperVisitor.visitLongWrapper(NumberWrapperVisitor.java:60)
	at org.seasar.doma.wrapper.LongWrapper.accept(LongWrapper.java:78)
	at org.seasar.doma.jdbc.entity.DefaultPropertyType.modifyIfNecessary(DefaultPropertyType.java:335)
	at org.seasar.doma.jdbc.entity.GeneratedIdPropertyType.setIfNecessary(GeneratedIdPropertyType.java:219)
	at org.seasar.doma.jdbc.entity.GeneratedIdPropertyType.postInsert(GeneratedIdPropertyType.java:202)
	at org.seasar.doma.jdbc.query.AutoInsertQuery.generateId(AutoInsertQuery.java:177)
	at org.seasar.doma.jdbc.command.InsertCommand.executeInternal(InsertCommand.java:37)
```

**Comment by nakamura-to** [comment]
詳細な報告ありがとうございます。
次のバージョンで修正します。
