### ISSUE TITLE
負荷時に [DOMA2015] [DOMA9001] Failed to get a message because of following error : java.util.MissingResourceException が出る

### ISSUE THREAD

**Issue by naokism** [domaframework/doma#77]
すいません、負荷時に以下のエラーが出ました。
環境は以下となります。
java build 1.8.0_20-b26
Tomcat 8.0.11
doma 2.0.1
MySQL 5.5.40
です。
こちらの作りが良くないのか、doma側なのか分かればいいのですが・・・

```
ERROR 2015-05-28 21:30:07,053 [ajp-nio-8029-exec-235] org.seasar.doma.jdbc.JdbcException: [DOMA2015] [DOMA9001] Failed to get a message because of following error : java.util.MissingResourceException: Can't find bundle for base name org.seasar.doma.internal.message.MessageResourceBundle, locale ja_JP
        at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:773)
        at org.seasar.doma.message.Message.getSimpleMessageInternal(Message.java:448)
        at org.seasar.doma.message.Message.getMessage(Message.java:435)
        at org.seasar.doma.DomaException.<init>(DomaException.java:62)
        at org.seasar.doma.jdbc.JdbcException.<init>(JdbcException.java:55)
        at org.seasar.doma.internal.jdbc.util.JdbcUtil.getConnection(JdbcUtil.java:42)
        at org.seasar.doma.jdbc.tx.LocalTransaction.lambda$getLocalTransactionContext$171(LocalTransaction.java:245)
        at org.seasar.doma.jdbc.tx.LocalTransaction$$Lambda$9/153667928.get(Unknown Source)
        at org.seasar.doma.jdbc.tx.LocalTransactionContext.getConnection(LocalTransactionContext.java:73)
        at org.seasar.doma.jdbc.tx.LocalTransactionDataSource.getConnectionInternal(LocalTransactionDataSource.java:124)
        at org.seasar.doma.jdbc.tx.LocalTransactionDataSource.getConnection(LocalTransactionDataSource.java:101)
        at org.seasar.doma.internal.jdbc.util.JdbcUtil.getConnection(JdbcUtil.java:40)
        at org.seasar.doma.jdbc.command.SelectCommand.execute(SelectCommand.java:60)
        at jp.xxxxxxxx.dao.ronly.impl.S2SessionDaoImpl.selectBySessionIdAndName(S2SessionDaoImpl.java:77)
        at jp.xxxxxxxx.servlet.ReverseProxyServlet.lambda$processRequest$28(ReverseProxyServlet.java:289)
        at jp.xxxxxxxx.servlet.ReverseProxyServlet$$Lambda$133/1955979288.get(Unknown Source)
        at org.seasar.doma.jdbc.tx.LocalTransactionManager.executeInTransaction(LocalTransactionManager.java:245)
        at org.seasar.doma.jdbc.tx.LocalTransactionManager.requiredInternal(LocalTransactionManager.java:96)
        at org.seasar.doma.jdbc.tx.LocalTransactionManager.required(LocalTransactionManager.java:75)
        at jp.xxxxxxxx.servlet.ReverseProxyServlet.processRequest(ReverseProxyServlet.java:287)
        at jp.xxxxxxxx.servlet.ReverseProxyServlet.doGet(ReverseProxyServlet.java:147)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:618)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.shindig.gadgets.servlet.ETagFilter.doFilter(ETagFilter.java:63)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:534)
        at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:827)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1566)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1523)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)

        at org.seasar.doma.internal.jdbc.util.JdbcUtil.getConnection(JdbcUtil.java:42)
        at org.seasar.doma.jdbc.tx.LocalTransaction.lambda$getLocalTransactionContext$171(LocalTransaction.java:245)
        at org.seasar.doma.jdbc.tx.LocalTransaction$$Lambda$9/153667928.get(Unknown Source)
        at org.seasar.doma.jdbc.tx.LocalTransactionContext.getConnection(LocalTransactionContext.java:73)
        at org.seasar.doma.jdbc.tx.LocalTransactionDataSource.getConnectionInternal(LocalTransactionDataSource.java:124)
        at org.seasar.doma.jdbc.tx.LocalTransactionDataSource.getConnection(LocalTransactionDataSource.java:101)
        at org.seasar.doma.internal.jdbc.util.JdbcUtil.getConnection(JdbcUtil.java:40)
        at org.seasar.doma.jdbc.command.SelectCommand.execute(SelectCommand.java:60)
        at jp.xxxxxxxx.dao.ronly.impl.S2SessionDaoImpl.selectBySessionIdAndName(S2SessionDaoImpl.java:77)
        at jp.xxxxxxxx.servlet.ReverseProxyServlet.lambda$processRequest$28(ReverseProxyServlet.java:289)
        at jp.xxxxxxxx.servlet.ReverseProxyServlet$$Lambda$133/1955979288.get(Unknown Source)
        at org.seasar.doma.jdbc.tx.LocalTransactionManager.executeInTransaction(LocalTransactionManager.java:245)
        at org.seasar.doma.jdbc.tx.LocalTransactionManager.requiredInternal(LocalTransactionManager.java:96)
        at org.seasar.doma.jdbc.tx.LocalTransactionManager.required(LocalTransactionManager.java:75)
        at jp.xxxxxxxx.servlet.ReverseProxyServlet.processRequest(ReverseProxyServlet.java:287)
        at jp.xxxxxxxx.servlet.ReverseProxyServlet.doGet(ReverseProxyServlet.java:147)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:618)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.shindig.gadgets.servlet.ETagFilter.doFilter(ETagFilter.java:63)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:534)
        at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:827)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1566)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1523)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: Cannot get a connection, general error
        at org.apache.tomcat.dbcp.dbcp2.PoolingDataSource.getConnection(PoolingDataSource.java:130)
        at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1412)
        at org.seasar.doma.internal.jdbc.util.JdbcUtil.getConnection(JdbcUtil.java:40)
        ... 40 more
Caused by: java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
        at org.apache.tomcat.dbcp.pool2.impl.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:548)
        at org.apache.tomcat.dbcp.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:437)
        at org.apache.tomcat.dbcp.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
        at org.apache.tomcat.dbcp.dbcp2.PoolingDataSource.getConnection(PoolingDataSource.java:118)
        ... 42 more
```

S2SessionDaoImplの 77行目は以下のコードでした。
```
java.sql.Blob __result = __command.execute();
```

以上、お手数かけしますがよろしくお願いします。

**Comment by naokism** [comment]
DB Connection数が足りないだけですかね・・・

**Comment by nakamura-to** [comment]
メッセージの取得に失敗しているのはDomaの問題です。もし、正常に取得できると「java.sql.Connectionの取得に失敗しました。原因は次のものです。 ...」というメッセージで、`org.seasar.doma.jdbc.JdbcException`がスローされます。
しかし、 `JdbcException`がスローされる原因となるConnectionの取得の失敗については、アプリ側に責任があると言えます。

Domaがメッセージ取得に失敗する件は、次のバージョンで修正しようと思います。原因はまだよくわかっていませんが、デフォルトのClassLoaderでリソースバンドルをロードできないケースがあるのかもしれません。

**Comment by naokism** [comment]
メッセージ取得に関して理解致しました。
Connection取得に関してはアプリ側の設定を見直します。

ありがとうございました。
